# Generated by Django 5.0.3 on 2024-03-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="theme",
            new_name="name",
        ),
    ]
