# Generated by Django 5.0.3 on 2024-03-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(max_length=255),
        ),
    ]
