# Generated by Django 5.0.3 on 2024-03-24 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_task_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag",
                to="catalog.tag",
            ),
        ),
    ]
