# Generated by Django 5.0.3 on 2024-03-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.BooleanField(
                choices=[("Done", "Done"), ("Not done", "Not done")], default="Not done"
            ),
        ),
    ]
